export const exercises2022 = [
  {
    id: '2022-g1-losange',
    year: 2022,
    groupement: 1,
    title: 'Losange avec variable C',
    sourceUrl: 'https://www.devenirenseignant.gouv.fr/les-sujets-des-epreuves-ecrites-du-crpe-externe-et-du-crpe-externe-special-899',
    description:
      'EST MAT 1, Exercice 4 — Le Programme 1 utilise une variable C (valeur initiale C = 50) pour tracer un quadrilatère : répéter 4 fois { avancer de C pas, tourner de 90° }. Échelle : 1 cm = 10 pixels. Le Programme 2 utilise le Programme 1 en boucle en modifiant la variable C pour obtenir des carrés emboîtés.',
    question:
      '1) En prenant C = 50 et 1 cm pour 10 pixels, tracer la figure du Programme 1. 2) Quelle est la nature de la figure tracée ? Justifier. 3) Quelles valeurs attribuer à A et N dans le Programme 2 ?',
    blocks: [
      { type: 'mettreVariable', args: ['C', 50], category: 'variables' },
      { type: 'styloPoser', args: [], category: 'pen' },
      {
        type: 'repeter',
        args: [4],
        category: 'control',
        body: [
          { type: 'avancer', args: [{ type: 'variable', name: 'C' }], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
        ],
      },
    ],
    hints: [
      'Le Programme 1 trace un quadrilatère avec 4 côtés de C pas et des angles de 90°.',
      'Un carré est un losange particulier (losange à angles droits).',
      'Pour le Programme 2, observer comment la variable C évolue à chaque itération.',
    ],
    answer:
      'Le Programme 1 trace un carré de côté 50 pas = 5 cm (4 côtés égaux, 4 angles droits). Un carré est un cas particulier de losange (losange à angles droits). Pour le Programme 2, A est la valeur ajoutée à C après chaque carré et N le nombre de répétitions.',
  },
  {
    id: '2022-g2-adam',
    year: 2022,
    groupement: 2,
    title: "Programme d'Adam",
    sourceUrl: 'https://www.devenirenseignant.gouv.fr/les-sujets-des-epreuves-ecrites-du-crpe-externe-et-du-crpe-externe-special-899',
    type: 'calcul',
    description: "CRPE 2022, Groupement 2, Exercice 4 — Adam a créé un programme de calcul dans Scratch. L'utilisateur choisit un nombre x, l'élève au carré, soustrait 3, multiplie par 2, puis soustrait le nombre de départ. Cela donne f(x) = (x²−3)×2 − x = 2x²−x−6.",
    question: "Exécuter le programme pour différentes valeurs de x. Montrer que pour tout nombre x, le programme retourne 2x²−x−6. Factoriser cette expression.",
    blocks: [
      { type: 'demander', args: ['x', 3], category: 'sensing' },
      { type: 'mettreVariableOp', args: ['résultat', { type: 'variable', name: 'x' }, '*', { type: 'variable', name: 'x' }], category: 'operators' },
      { type: 'ajouterVariable', args: ['résultat', -3], category: 'variables' },
      { type: 'mettreVariableOp', args: ['résultat', { type: 'variable', name: 'résultat' }, '*', 2], category: 'operators' },
      { type: 'mettreVariableOp', args: ['résultat', { type: 'variable', name: 'résultat' }, '-', { type: 'variable', name: 'x' }], category: 'operators' },
    ],
    hints: [
      "pour x=2 : 2×(2²)−2−6 = 8−2−6 = 0 ✔",
      'Pour tout x : résultat = x², puis −3 → x²−3, puis ×2 → 2x²−6, puis −x → 2x²−x−6',
      'On peut factoriser : 2x²−x−6 = (2x+3)(x−2)',
    ],
    answer: 'Pour tout x : x²→x²−3→2(x²−3)=2x²−6→2x²−6−x=2x²−x−6. Factorisation : 2x²−x−6 = (2x+3)(x−2). Pour x=3 : 2(9)−3−6 = 9. Pour x=0 : −6. Pour x=2 : 0.',
  },
  {
    id: '2022-g3-tirets',
    year: 2022,
    groupement: 3,
    title: 'Tirets et transformations',
    sourceUrl: 'https://www.devenirenseignant.gouv.fr/les-sujets-des-epreuves-ecrites-du-crpe-externe-et-du-crpe-externe-special-899',
    description: "Un programme Scratch trace des tirets. Le lutin est initialement orienté vers la droite (90°).",
    subExercises: [
      {
        id: '2022-g3-tirets-q1',
        subtitle: 'Q1 — Figure originale',
        description: 'Exécuter le programme tel quel : le lutin trace un tiret, avance sans tracer, puis tourne de 90°. Répéter 4 fois.',
        question: 'Représenter la figure obtenue (1 mm = 1 pixel).',
        blocks: [
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'repeter', args: [4], category: 'control', body: [
            { type: 'avancer', args: [10], category: 'motion' },
            { type: 'styloRelever', category: 'pen' },
            { type: 'avancer', args: [10], category: 'motion' },
            { type: 'tournerDroite', args: [90], category: 'motion' },
            { type: 'styloPoser', category: 'pen' },
          ]},
        ],
        answer: 'On obtient un L composé de 4 tirets formant un carré ouvert.',
      },
      {
        id: '2022-g3-tirets-q2',
        subtitle: 'Q2 — Tirets en ligne',
        description: 'Marie modifie le programme : répéter 8 fois, sans tourner.',
        question: 'Quelles modifications apporter pour obtenir 8 tirets alignés horizontalement ?',
        blocks: [
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'repeter', args: [8], category: 'control', body: [
            { type: 'avancer', args: [10], category: 'motion' },
            { type: 'styloRelever', category: 'pen' },
            { type: 'avancer', args: [10], category: 'motion' },
            { type: 'styloPoser', category: 'pen' },
          ]},
        ],
        answer: "Supprimer le bloc 'tourner' et passer le répéter à 8 fois.",
      },
      {
        id: '2022-g3-tirets-q3',
        subtitle: 'Q3 — Tirets en étoile',
        description: 'Lo modifie le programme pour obtenir des tirets en étoile. Tourner de 45° au lieu de 90°, répéter 8 fois.',
        question: "Quelles modifications pour obtenir une étoile de tirets ? Quelle transformation géométrique passe d'un tiret à l'autre ?",
        blocks: [
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'repeter', args: [8], category: 'control', body: [
            { type: 'avancer', args: [10], category: 'motion' },
            { type: 'styloRelever', category: 'pen' },
            { type: 'avancer', args: [10], category: 'motion' },
            { type: 'tournerDroite', args: [45], category: 'motion' },
            { type: 'styloPoser', category: 'pen' },
          ]},
        ],
        answer: 'Changer 90° en 45° et répéter 8 fois. La transformation est une rotation de 45°.',
      },
    ],
    blocks: [],
    hints: [
      'Q1 : Le lutin trace un tiret de 10 px, avance sans tracer de 10 px, puis tourne de 90°.',
      'Q2 : Sans le bloc tourner, les tirets restent alignés horizontalement.',
      'Q3 : Avec 45° au lieu de 90°, les tirets forment une étoile (8 × 45° = 360°).',
    ],
    answer: 'Q1 : carré ouvert de tirets. Q2 : 8 tirets en ligne. Q3 : étoile de tirets (rotation de 45°).',
  },
  {
    id: '2022-g4-patron-cube',
    year: 2022,
    groupement: 4,
    source: 'entrainement',
    title: 'Patron de cube',
    sourceUrl: 'https://www.devenirenseignant.gouv.fr/les-sujets-des-epreuves-ecrites-du-crpe-externe-et-du-crpe-externe-special-899',
    description: "Une enseignante veut faire construire des dés cubiques de 3 cm de côté avec Scratch. 1 pas = 0.05 cm, donc 60 pas = 3 cm. Le bloc 'carré' trace un carré de 60 pas puis avance de 60 pas stylo relevé.",
    subExercises: [
      {
        id: '2022-g4-patron-q1',
        subtitle: 'Q1 — Patron en croix',
        description: 'Compléter le bloc carré (avancer 60, tourner 90°, répéter 4 fois) puis ordonner les instructions pour tracer le patron en croix.',
        blocks: [
          { type: 'definirBloc', args: ['carré'], category: 'custom', body: [
            { type: 'styloPoser', category: 'pen' },
            { type: 'repeter', args: [4], category: 'control', body: [
              { type: 'avancer', args: [60], category: 'motion' },
              { type: 'tournerDroite', args: [90], category: 'motion' },
            ]},
            { type: 'styloRelever', category: 'pen' },
            { type: 'avancer', args: [60], category: 'motion' },
          ]},
          { type: 'appelerBloc', args: ['carré'], category: 'custom' },
          { type: 'appelerBloc', args: ['carré'], category: 'custom' },
          { type: 'appelerBloc', args: ['carré'], category: 'custom' },
          { type: 'appelerBloc', args: ['carré'], category: 'custom' },
          { type: 'ajouterY', args: [60], category: 'motion' },
          { type: 'ajouterX', args: [-180], category: 'motion' },
          { type: 'appelerBloc', args: ['carré'], category: 'custom' },
          { type: 'ajouterY', args: [-120], category: 'motion' },
          { type: 'ajouterX', args: [-60], category: 'motion' },
          { type: 'appelerBloc', args: ['carré'], category: 'custom' },
        ],
        answer: 'Le patron forme une croix de 6 carrés.',
      },
      {
        id: '2022-g4-patron-q2',
        subtitle: 'Q2 — Second patron',
        description: "Un second algorithme utilise deux boucles imbriquées : répéter 2 fois { carré, répéter 3 fois { ajouter -60 à x }, ajouter -60 à y }.",
        question: 'Dessiner ce patron à main levée.',
        blocks: [
          { type: 'definirBloc', args: ['carré'], category: 'custom', body: [
            { type: 'styloPoser', category: 'pen' },
            { type: 'repeter', args: [4], category: 'control', body: [
              { type: 'avancer', args: [60], category: 'motion' },
              { type: 'tournerDroite', args: [90], category: 'motion' },
            ]},
            { type: 'styloRelever', category: 'pen' },
            { type: 'avancer', args: [60], category: 'motion' },
          ]},
          { type: 'repeter', args: [2], category: 'control', body: [
            { type: 'appelerBloc', args: ['carré'], category: 'custom' },
            { type: 'repeter', args: [3], category: 'control', body: [
              { type: 'ajouterX', args: [-60], category: 'motion' },
            ]},
            { type: 'ajouterY', args: [-60], category: 'motion' },
          ]},
        ],
        answer: "On obtient un patron en L : 1 carré en haut à gauche, puis 3 en dessous formant une colonne décalée.",
      },
    ],
    blocks: [],
    hints: [
      "Le bloc 'carré' trace un carré de 60 pas de côté puis avance de 60 pas stylo relevé.",
      "Pour le patron en croix, il faut positionner 6 carrés en forme de +.",
      'Le second patron utilise des boucles imbriquées pour positionner les carrés.',
    ],
    answer: "Q1 : patron en croix (6 carrés). Q2 : patron en L (2 carrés alignés puis décalés).",
  },
]
