export const exercises2024 = [
  {
    id: '2024-g1-geoplan',
    year: 2024,
    groupement: 1,
    title: 'Géoplan Scratch',
    sourceUrl: 'https://www.devenirenseignant.gouv.fr/les-sujets-des-epreuves-ecrites-du-crpe-externe-et-du-crpe-externe-special-899',
    description:
      "EST MAT 1, Exercice 5, Partie B.3 — Un programme Scratch construit une figure sur un géoplan de 25 picots (deux picots contigus = 3 cm). Échelle : 3 cm = 70 pas. Le point de départ est (−140 ; 140). Le lutin s'oriente à 90° (vers la droite). Il faut déterminer les valeurs de A, B et C.",
    question:
      'En prenant 3 cm pour 70 pas, déterminer les valeurs attribuées aux lettres A, B et C pour que le script permette de construire la figure.',
    blocks: [
      { type: 'effacer', args: [], category: 'pen' },
      { type: 'allerA', args: [-140, 140], category: 'motion' },
      { type: 'orienter', args: [90], category: 'motion' },
      { type: 'setEpaisseur', args: [3], category: 'pen' },
      { type: 'styloPoser', args: [], category: 'pen' },
      { type: 'avancer', args: [210], category: 'motion' },
      { type: 'tournerDroite', args: [90], category: 'motion' },
      { type: 'avancer', args: [70], category: 'motion' },
      { type: 'tournerDroite', args: [135], category: 'motion' },
      { type: 'avancer', args: [99], category: 'motion' },
      { type: 'tournerDroite', args: [135], category: 'motion' },
      { type: 'avancer', args: [280], category: 'motion' },
      { type: 'styloRelever', args: [], category: 'pen' },
    ],
    hints: [
      '3 cm = 70 pas (1 case). 210 pas = 3 cases horizontales.',
      'La diagonale B : 3 cases en diagonale = 3√2 cm ≈ 4,24 cm ≈ 99 pas.',
      'A = 135° : depuis l\'orientation vers le bas (après tourner 90°), tourner encore 135° oriente vers le haut-gauche.',
      'C = 135° : même logique pour clore la figure vers la gauche.',
    ],
    answer:
      "A = 135° (angle pour s'orienter en diagonale vers le haut-gauche), B ≈ 99 pas (diagonale de 3 cases = 3√2 cm × 70/3 ≈ 98,99 pas, arrondi à 99), C = 135° (angle pour s'orienter vers la gauche). Échelle : 3 cm = 70 pas.",
    corrige: {
      figure: "Trapèze rectangle sur géoplan : 3 cases à droite, 1 case en bas, diagonale de 3√2 cases, 4 cases à gauche",
      variables: { A: "135°", B: "99 pas (3√2 cm)", C: "135°" },
      etapes: [
        "Départ : (−140, 140), orientation 90° (droite)",
        "Avancer 210 pas (3 cases = 3×70) → point (70, 140)",
        "Tourner droite 90° → orientation 180° (bas)",
        "Avancer 70 pas (1 case) → point (70, 70)",
        "Tourner droite A=135° → orientation 315° (diagonale haut-gauche)",
        "Avancer B=99 pas (3√2 cm ≈ 3×1,414×70/3 ≈ 99) → remonte en diagonale",
        "Tourner droite C=135° → orientation 90° (droite), donc gauche = 270°",
        "Avancer 280 pas pour fermer la figure",
      ],
      erreurs_classiques: [
        "Oublier de calculer B avec Pythagore : B = 3√2 × 70/3 = 70√2 ≈ 99",
        "Confondre A et C (les deux valent 135° dans cet exercice)",
        "Mal lire l'échelle : 3 cm = 70 pas, donc 1 cm ≠ 10 pas ici",
      ],
      difficulte: 4,
    },
  },
  {
    id: '2024-g2-calcul',
    year: 2024,
    groupement: 2,
    title: 'Programme de calcul x² + 3x − 4',
    sourceUrl: 'https://www.devenirenseignant.gouv.fr/les-sujets-des-epreuves-ecrites-du-crpe-externe-et-du-crpe-externe-special-899',
    type: 'calcul',
    description:
      'EST MAT 2, Exercice 3 — Un script Scratch exécute un programme de calcul : choisir x, calculer x², ajouter 3x, soustraire 4. Le résultat est x² + 3x − 4.',
    question:
      'Exécuter le programme pour différentes valeurs de x. Montrer que le résultat est x² + 3x − 4. Factoriser cette expression.',
    blocks: [
      { type: 'demander', args: ['x', 5], category: 'sensing' },
      { type: 'mettreVariableOp', args: ['résultat', { type: 'variable', name: 'x' }, '*', { type: 'variable', name: 'x' }], category: 'operators' },
      { type: 'mettreVariableOp', args: ['résultat', { type: 'variable', name: 'résultat' }, '+', { type: 'op', op: '*', left: { type: 'variable', name: 'x' }, right: 3 }], category: 'operators' },
      { type: 'ajouterVariable', args: ['résultat', -4], category: 'variables' },
    ],
    hints: [
      'Le programme calcule x² + 3x − 4.',
      'Pour x=5 : 25 + 15 − 4 = 36.',
      'On peut factoriser : x² + 3x − 4 = (x − 1)(x + 4).',
      'Pour x=1 : 1 + 3 − 4 = 0. Pour x=−4 : 16 − 12 − 4 = 0.',
    ],
    answer:
      'Le résultat est x² + 3x − 4 = (x − 1)(x + 4). Pour x=5 : 36. Pour x=1 : 0. Pour x=−4 : 0.',
    corrige: {
      figure: "Programme de calcul — résultat : x² + 3x − 4",
      variables: { "f(x)": "x² + 3x − 4", "factorisation": "(x−1)(x+4)", "racines": "x=1 ou x=−4" },
      etapes: [
        "Étape 1 : résultat ← x × x = x²",
        "Étape 2 : résultat ← x² + 3x",
        "Étape 3 : résultat ← x² + 3x − 4",
        "Factorisation : somme des racines = −3 (= −1+−4), produit = −4 (= −1×4) → (x−1)(x+4)",
        "Vérification : (x−1)(x+4) = x²+4x−x−4 = x²+3x−4 ✓",
      ],
      erreurs_classiques: [
        "Confondre les signes dans la factorisation : (x+1)(x−4) donne x²−3x−4, pas x²+3x−4",
        "Ne pas vérifier la factorisation en développant",
      ],
      difficulte: 2,
    },
  },
  {
    id: '2024-g3-figure-base',
    year: 2024,
    groupement: 3,
    title: 'Figure de base — Carré puis triangle',
    sourceUrl: 'https://www.devenirenseignant.gouv.fr/les-sujets-des-epreuves-ecrites-du-crpe-externe-et-du-crpe-externe-special-899',
    description:
      'EST MAT 3, Exercice 4 — Un script utilise un bloc « figure_de_base » avec une variable « longueur ». Le script initial trace des carrés. On demande ensuite de modifier le bloc pour tracer des triangles équilatéraux et de comparer les aires.',
    question:
      '1) Quelle est la nature de la figure de base ? 2) Tracer la figure obtenue après clic sur le drapeau vert. 3a) Quelles modifications pour obtenir un triangle équilatéral ? 3b) Quel est le rapport entre les aires des deux triangles ?',
    blocks: [
      { type: 'mettreVariable', args: ['longueur', 50], category: 'variables' },
      { type: 'styloPoser', args: [], category: 'pen' },
      {
        type: 'repeter',
        args: [4],
        category: 'control',
        body: [
          { type: 'avancer', args: [{ type: 'variable', name: 'longueur' }], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
        ],
      },
      { type: 'ajouterVariable', args: ['longueur', 50], category: 'variables' },
      {
        type: 'repeter',
        args: [4],
        category: 'control',
        body: [
          { type: 'avancer', args: [{ type: 'variable', name: 'longueur' }], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
        ],
      },
    ],
    hints: [
      'La figure de base répète 4 fois avec angle 90° → c\'est un carré.',
      'Pour un triangle équilatéral : 3 répétitions, angle extérieur 120°.',
      'Le rapport des aires de figures semblables est le carré du rapport de similitude.',
    ],
    answer:
      '1) Carré (4 côtés, angle 90°). 2) Deux carrés emboîtés de côtés 50 et 100. 3a) Remplacer 4 par 3 et 90° par 120°. 3b) Le rapport de similitude est 100/50 = 2, donc le rapport des aires est 2² = 4.',
  },
  {
    id: '2024-mat4-touches',
    year: 2024,
    title: 'Segments directionnels — Touches a, b, c',
    sourceUrl: 'https://www.devenirenseignant.gouv.fr/les-sujets-des-epreuves-ecrites-du-crpe-externe-et-du-crpe-externe-special-899',
    description: "EST MAT 4 (Supplémentaire Créteil-Versailles), Exercice 3 — Trois programmes Scratch associés aux touches a, b, c tracent des segments. Touche a : horizontal droite 40 pas. Touche b : vertical haut 40 pas. Touche c : L inversé (droite 40 + descente 40).",
    subExercises: [
      {
        id: '2024-mat4-q1',
        subtitle: 'Q1 — Figure impossible',
        description: "Programme touche a : orienter 90°, styloPoser, avancer 40, styloRelever. Touche b : orienter 0°, styloPoser, avancer 40, styloRelever. Touche c : orienter 90°, styloPoser, avancer 40, tournerDroite 90°, avancer 40, styloRelever.",
        question: "Parmi les 3 propositions de figures, laquelle ne peut pas être réalisée par un enchaînement de touches a, b, c ? Expliquer.",
        blocks: [
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
        ],
        answer: "La Proposition 2 est impossible : elle nécessite un segment diagonal (à 45°). Les touches a (→), b (↑) et c (L inversé) ne permettent de tracer que des segments horizontaux ou verticaux. Aucun enchaînement ne produit de diagonale.",
      },
      {
        id: '2024-mat4-q2',
        subtitle: 'Q2 — Figure c c c a a c c b b',
        description: "Tracer la figure obtenue après l'enchaînement de touches : c c c a a c c b b. Échelle : 1 cm = 10 pas.",
        question: "En prenant 1 cm pour 10 pas, tracer la figure obtenue après avoir réalisé l'enchaînement c c c a a c c b b.",
        blocks: [
          { type: 'allerA', args: [-100, 50], category: 'motion' },
          { type: 'orienter', args: [90], category: 'motion' },
          // c × 3
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
          // a × 2
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
          // c × 2
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
          // b × 2
          { type: 'orienter', args: [0], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
          { type: 'orienter', args: [0], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
        ],
        answer: "L'enchaînement c c c produit 3 L (horizontal+descente). Puis a a ajoute 2 segments horizontaux. Puis c c ajoute 2 L supplémentaires. Enfin b b trace 2 segments verticaux vers le haut. La figure ressemble à un escalier irrégulier.",
      },
      {
        id: '2024-mat4-q3',
        subtitle: 'Q3 — Rectangle 80×60 (diagonale 100)',
        description: "Un Programme d est ajouté : s'orienter vers la gauche (−90° ou 270°), poser stylo, avancer N pas, relever stylo. Construire un rectangle de longueur 80 pas dont les diagonales mesurent 100 pas.",
        question: "Donner un enchaînement de touches permettant d'obtenir un rectangle de longueur 80 pas et dont les diagonales mesurent 100 pas. Expliquer le raisonnement.",
        blocks: [
          { type: 'allerA', args: [-40, 30], category: 'motion' },
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [80], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
          { type: 'orienter', args: [-90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [60], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [80], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
          { type: 'orienter', args: [0], category: 'motion' },
          { type: 'styloPoser', category: 'pen' },
          { type: 'avancer', args: [60], category: 'motion' },
          { type: 'styloRelever', category: 'pen' },
        ],
        answer: "Raisonnement : les diagonales d'un rectangle sont égales. Diagonale = 100, longueur = 80. Par Pythagore : largeur = √(100²−80²) = √(10000−6400) = √3600 = 60 pas. Enchaînement : a(80) b_inverse(60) d(80) b(60) — soit 2 longueurs et 2 largeurs en faisant le tour du rectangle.",
        hints: [
          "Les diagonales d'un rectangle sont égales et se coupent en leur milieu.",
          "Pythagore : si diagonale = 100 et longueur = 80, alors largeur = √(100²−80²) = 60.",
          "Pour aller vers la gauche, utiliser la touche d (orienter −90°).",
          "Un enchaînement possible : a (→80), descendre 60, d (←80), monter 60.",
        ],
      },
      {
        id: '2024-Suppl-3d',
        subtitle: 'Q4 — Touche d — Rectangle avec diagonales de 100 pas',
        description: "Un programme d est ajouté : s'orienter vers le bas, avancer de N pas, relever le stylo, avancer de N pas.",
        question: "Donner un enchaînement de touches (a, b, c, d) pour obtenir un rectangle de longueur 80 pas dont les diagonales mesurent 100 pas.",
        type: 'quiz',
        blocks: [
          { type: 'allerA', args: [-40, 30], category: 'motion' },
          { type: 'orienter', args: [180], category: 'motion' },
          { type: 'styloPoser', args: [], category: 'pen' },
          { type: 'avancer', args: [60], category: 'motion' },
          { type: 'styloRelever', args: [], category: 'pen' },
          { type: 'avancer', args: [60], category: 'motion' },
        ],
        answer: "La largeur du rectangle : si longueur=80 et diagonale=100, alors par Pythagore la largeur=60 (car 60²+80²=100²). Enchaînement : a a (80 pas vers la droite), d (60 pas vers le bas), a a (80 pas vers la droite), b b (60 pas vers le haut). Ou équivalent avec c.",
      },
    ],
    blocks: [],
    hints: [
      "Touche a : segment horizontal vers la droite (40 pas).",
      "Touche b : segment vertical vers le haut (40 pas).",
      "Touche c : angle droit (horizontal 40 pas puis descente 40 pas — forme un L).",
      "Aucune touche ne permet un segment diagonal.",
      "Q3 : utiliser Pythagore pour trouver la largeur du rectangle.",
    ],
    answer: "Q1 : Proposition 2 impossible (segment diagonal). Q2 : figure en escalier irrégulier. Q3 : rectangle 80×60 (largeur calculée par Pythagore : √(100²−80²) = 60 pas). Q4 : enchaînement a a d a a b b.",
  },
]
