export const exercises2025 = [
  {
    id: '2025-1',
    year: 2025,
    groupement: 1,
    title: 'Programme incomplet — Trouver M, N, P, R, T',
    sourceUrl: 'https://www.devenirenseignant.gouv.fr/les-sujets-des-epreuves-ecrites-du-crpe-externe-et-du-crpe-externe-special-899',
    type: 'quiz',
    description:
      "EST MAT 1, Exercice — Le programme Scratch incomplet permet de construire la figure 4 en partant de l'origine (0,0). Échelle : 1 cm = 20 pas. L'instruction « s'orienter à 90 » oriente le lutin vers la droite. Les lettres M, N, P, R, T désignent des paramètres de longueur (en pas) et d'angle à déterminer.",
    question:
      "Déterminer les valeurs à attribuer aux lettres M, N, P, R et T pour que le script construise la figure 4. (Aucune justification attendue)",
    blocks: [
      { type: 'effacer', args: [], category: 'pen' },
      { type: 'allerA', args: [0, 0], category: 'motion' },
      { type: 'orienter', args: [90], category: 'motion' },
      { type: 'styloPoser', args: [], category: 'pen' },
      { type: 'mettreVariable', args: ['M', '?'], category: 'variables' },
      { type: 'mettreVariable', args: ['N', '?'], category: 'variables' },
      { type: 'mettreVariable', args: ['P', '?'], category: 'variables' },
      { type: 'mettreVariable', args: ['R', '?'], category: 'variables' },
      { type: 'mettreVariable', args: ['T', '?'], category: 'variables' },
      {
        type: 'repeter',
        args: [{ type: 'variable', name: 'T' }],
        category: 'control',
        body: [
          { type: 'avancer', args: [{ type: 'variable', name: 'M' }], category: 'motion' },
          { type: 'tournerDroite', args: [{ type: 'variable', name: 'N' }], category: 'motion' },
          { type: 'avancer', args: [{ type: 'variable', name: 'P' }], category: 'motion' },
          { type: 'tournerDroite', args: [{ type: 'variable', name: 'R' }], category: 'motion' },
        ],
      },
    ],
    hints: [
      "Échelle : 1 cm = 20 pas. Les longueurs sont des multiples de 20.",
      "M et P sont des longueurs de côtés (en pas). N et R sont des angles de rotation (en degrés).",
      "T est le nombre de répétitions. Pour un polygone régulier à T côtés : T × angle_extérieur = 360°.",
      "L'image de la figure 4 du sujet officiel est indispensable pour déterminer les valeurs exactes.",
    ],
    answer:
      "Exercice nécessitant l'image de la figure 4 du sujet officiel pour déterminer les valeurs exactes. M, N, P, R, T sont des paramètres de longueur (en pas) et d'angle. Avec 1 cm = 20 pas, les longueurs sont des multiples de 20 et les angles sont des valeurs simples (90°, 45°, 135°…). Se référer au sujet CRPE 2025 Groupement 1 (EST MAT 1) pour la figure 4.",
    corrige: {
      figure: "Figure 4 du sujet CRPE 2025 Gr1 — valeurs exactes à lire sur le sujet officiel",
      variables: { M: '?', N: '?', P: '?', R: '?', T: '?' },
      etapes: [
        "Identifier la figure 4 sur le sujet officiel CRPE 2025 Groupement 1",
        "Mesurer les longueurs des côtés (convertir en pas : longueur_cm × 20)",
        "Identifier les angles de rotation (N et R) à partir de la géométrie de la figure",
        "Compter le nombre de répétitions T",
      ],
      erreurs_classiques: [
        "Oublier la conversion 1 cm = 20 pas",
        "Confondre angle intérieur et angle extérieur (le programme utilise l'angle de rotation = angle extérieur)",
      ],
      difficulte: 3,
    },
  },
  {
    id: '2025-g2-triangle-iso',
    year: 2025,
    groupement: 2,
    title: 'Triangle rectangle isocèle',
    sourceUrl: 'https://www.devenirenseignant.gouv.fr/les-sujets-des-epreuves-ecrites-du-crpe-externe-et-du-crpe-externe-special-899',
    description:
      "EST MAT 2, Exercice 5 — Le programme demande la valeur de « a » puis trace un triangle rectangle isocèle. Le lutin s'oriente à 90° au départ. Programme de base (a=40) : avancer a, tourner droite 90°, avancer a, tourner droite 135°, avancer a√2, tourner droite 135°, avancer a, tourner droite 90°.\nProgramme A : ajoute « avancer de a+10 pas » à la fin → décale le départ vers la droite.\nProgramme B : supprime le dernier « avancer a » et « tourner droite 90° » → triangle sans retour.\nProgramme C : ajoute « ajouter 10 à a » à la fin → triangles de taille croissante.",
    question:
      "1) Pour a = 40, tracer la figure obtenue (1 cm = 10 pas). 2) Indiquer l'orientation du lutin à la fin. 3) Associer chaque programme modifié (A, B, C) à la figure correspondante parmi les figures 1 à 4.",
    subExercises: [
      {
        subtitle: "Q1 — Programme de base (a=40)",
        description: "Le programme de base trace un triangle rectangle isocèle pour a = 40.",
        question: "Tracer la figure obtenue pour a = 40 (1 cm = 10 pas). Indiquer l'orientation finale du lutin.",
        blocks: [
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', args: [], category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [135], category: 'motion' },
          { type: 'avancer', args: [57], category: 'motion' },
          { type: 'tournerDroite', args: [135], category: 'motion' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
        ],
        answer: "Triangle rectangle isocèle de côtés 40 pas et hypoténuse ≈ 57 pas. Orientation finale : 90° (vers la droite, après un tour complet de 90+135+135+90=450° = 360°+90°).",
      },
      {
        subtitle: "Programme A → Figure 2",
        description: "Programme A : programme de base + « avancer de a+10 pas » (soit 50 pas) à la fin. Chaque répétition décale le point de départ vers la droite.",
        question: "À quelle figure correspond le programme A ?",
        blocks: [
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', args: [], category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [135], category: 'motion' },
          { type: 'avancer', args: [57], category: 'motion' },
          { type: 'tournerDroite', args: [135], category: 'motion' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
          { type: 'avancer', args: [50], category: 'motion' },
        ],
        answer: "Programme A → Figure 2 : triangles en escalier vers la droite. Le lutin avance de a+10=50 pas après chaque triangle, décalant le départ.",
      },
      {
        subtitle: "Programme B → Figure 4",
        description: "Programme B : programme de base sans le dernier « avancer a » ni « tourner droite 90° ».",
        question: "À quelle figure correspond le programme B ?",
        blocks: [
          { type: 'orienter', args: [90], category: 'motion' },
          { type: 'styloPoser', args: [], category: 'pen' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [90], category: 'motion' },
          { type: 'avancer', args: [40], category: 'motion' },
          { type: 'tournerDroite', args: [135], category: 'motion' },
          { type: 'avancer', args: [57], category: 'motion' },
        ],
        answer: "Programme B → Figure 4 : grand triangle avec diagonales parallèles à l'intérieur. Sans le retour, chaque triangle partage la diagonale du suivant.",
      },
      {
        subtitle: "Programme C → Figure 3",
        description: "Programme C : programme de base + « ajouter 10 à a » à la fin. Triangles de taille croissante (a = 40, 50, 60, 70…). L'hypoténuse vaut a×√2 (calculée dynamiquement).",
        question: "À quelle figure correspond le programme C ?",
        blocks: [
          { type: 'mettreVariable', args: ['a', 30], category: 'variables' },
          { type: 'repeter', args: [4], category: 'control', body: [
            { type: 'ajouterVariable', args: ['a', 10], category: 'variables' },
            { type: 'orienter', args: [90], category: 'motion' },
            { type: 'styloPoser', args: [], category: 'pen' },
            { type: 'avancer', args: [{ type: 'variable', name: 'a' }], category: 'motion' },
            { type: 'tournerDroite', args: [90], category: 'motion' },
            { type: 'avancer', args: [{ type: 'variable', name: 'a' }], category: 'motion' },
            { type: 'tournerDroite', args: [135], category: 'motion' },
            { type: 'avancer', args: [{ type: 'op', op: '*', left: { type: 'variable', name: 'a' }, right: { type: 'op', op: 'sqrt', left: 2 } }], category: 'motion' },
            { type: 'tournerDroite', args: [135], category: 'motion' },
            { type: 'avancer', args: [{ type: 'variable', name: 'a' }], category: 'motion' },
            { type: 'tournerDroite', args: [90], category: 'motion' },
          ]},
        ],
        answer: "Programme C → Figure 3 : triangles de taille croissante vers la gauche. La valeur de a augmente de 10 à chaque itération (40, 50, 60, 70…). L'hypoténuse = a×√2.",
      },
    ],
    blocks: [],
    hints: [
      "Le triangle rectangle isocèle a un angle de 90° et deux angles de 45°.",
      "L'hypoténuse = a√2 ≈ 40 × 1,414 ≈ 56,6 pas (arrondi à 57 pas).",
      "Programme A → Figure 2 : triangles identiques décalés vers la droite.",
      "Programme B → Figure 4 : triangles imbriqués partageant la diagonale.",
      "Programme C → Figure 3 : triangles de taille croissante.",
    ],
    answer:
      "1) Triangle rectangle isocèle de côtés 40 pas (4 cm) et hypoténuse ≈ 57 pas. 2) Orientation finale : 90° (tour complet : 90+135+135+90=450°=360°+90°). 3) Programme A → Figure 2, Programme B → Figure 4, Programme C → Figure 3.",
    corrige: {
      figure: "Triangle rectangle isocèle de cathètes a pas et d'hypoténuse a√2 pas",
      variables: { a: 40, hypotenuse: "a√2 ≈ 57", orientation_finale: "90°" },
      etapes: [
        "Avancer a → premier côté horizontal",
        "Tourner droite 90° → pointer vers le bas",
        "Avancer a → second côté vertical",
        "Tourner droite 135° → pointer vers le haut-gauche (diagonale)",
        "Avancer a√2 → hypoténuse",
        "Tourner droite 135° → retour à 90° (orientation initiale)",
        "Somme des rotations : 90 + 135 + 135 = 360° → retour à l'orientation de départ (90°)",
      ],
      erreurs_classiques: [
        "Oublier que a√2 ≈ 1,414 × a (pas 1,5 × a)",
        "Calculer l'orientation finale en cumulant toutes les rotations sans faire mod 360°",
        "Confondre programme A (décalage) et C (taille croissante)",
      ],
      difficulte: 3,
    },
  },
]
